[package]
name = "winnow_datetime"
version = "0.4.0"
description = "Parsing dates using winnow"
keywords = [ "iso8601", "date-time", "parser", "winnow" ]
categories = [ "parser-implementations", "date-and-time" ]

repository = "https://github.com/soulstompp/winnow-datetime"
documentation = "https://docs.rs/winnow-datetime/"
license = "MIT"
readme = "README.md"

edition = "2021"

[package.metadata.docs.rs]
all-features = true

[dependencies]
winnow = "1.0"
chrono = { version = "0.4", default-features = false, optional = true }
jiff = {  version = "0.2.13", optional = true }
time = { version = "0.3.37", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["std"]
std = ["winnow/std"]
chrono = ["dep:chrono"]
jiff = ["dep:jiff"]
time = ["dep:time"]
serde = ["dep:serde"]
