[package]
name = "winnow-datetime-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
winnow_iso8601 = { path = "../crates/winnow-iso8601" }
winnow_rfc3339 = { path = "../crates/winnow-rfc3339" }
winnow_rfc9557 = { path = "../crates/winnow-rfc9557" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "parse_dates"
path = "fuzzers/parse_dates.rs"
test = false
doc = false
bench = false
