[package]
name = "winnow_rfc3339"
version = "0.4.0"
description = "Parsing RFC 3339 dates using winnow"
keywords = [ "rfc3339", "rfc-3339", "date-time", "parser", "winnow" ]
categories = [ "parser-implementations", "date-and-time" ]

repository = "https://github.com/soulstompp/winnow-datetime"
documentation = "https://docs.rs/winnow-rfc3339/"
license = "MIT"
readme = "README.md"

edition = "2021"

[package.metadata.docs.rs]
all-features = true

[dependencies]
winnow = {  version = "1.0" }
winnow_datetime = { path = "../winnow-datetime", version = "0.4" }

[dev-dependencies ]
winnow_datetime_assert = { path = "../winnow-datetime-assert", version = "0.4" }
libtest-mimic = "0.8.1"

[[test]]
name = "rfc3339_date_formats"
path="tests/formats/date.rs"
harness = false

[[test]]
name = "rfc3339_offset_formats"
path="tests/formats/offset.rs"
harness = false

[[test]]
name = "rfc3339_time_formats"
path="tests/formats/time.rs"
harness = false

[features]
default = ["std"]
std = ["winnow/std"]
chrono = ["winnow_datetime/chrono"]
jiff = ["winnow_datetime/jiff"]
serde = ["winnow_datetime/serde"]
time = ["winnow_datetime/time"]
