[package]
name = "winnow_rfc9557"
version = "0.2.0"
description = "Parsing RFC 9557 dates using winnow"
keywords = [ "rfc9557", "rfc-9557", "date-time", "parser", "winnow" ]
categories = [ "parser-implementations", "date-and-time" ]

repository = "https://github.com/soulstompp/winnow-datetime"
documentation = "https://docs.rs/winnow-rfc9557/"
license = "MIT"
readme = "README.md"

edition = "2021"

[package.metadata.docs.rs]
all-features = true

[dependencies]
winnow = {  version = "1.0" }
winnow_datetime = { path = "../winnow-datetime", version = "0.4" }

[dev-dependencies ]
winnow_datetime_assert = { path = "../winnow-datetime-assert", version = "0.4" }
libtest-mimic = "0.8.1"

[[test]]
name = "rfc9557_date_formats"
path="tests/formats/date.rs"
harness = false

[[test]]
name = "rfc9557_offset_formats"
path="tests/formats/offset.rs"
harness = false

[[test]]
name = "rfc9557_time_formats"
path="tests/formats/time.rs"
harness = false

[[test]]
name = "rfc9557_time_zone_formats"
path="tests/formats/time_zone.rs"
harness = false

[[test]]
name = "rfc9557_calendar_formats"
path="tests/formats/calendar.rs"
harness = false

[features]
default = ["std"]
std = ["winnow/std"]
chrono = ["winnow_datetime/chrono"]
jiff = ["winnow_datetime/jiff"]
serde = ["winnow_datetime/serde"]
time = ["winnow_datetime/time"]
